name: Mark or Close Stale Issues

on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Mark or close
        run: |
          ./tools/stale-issues.rb ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
